```{r kNN_mice_{{id}}, include=FALSE, warning=FALSE, message=FALSE}
load_result_raw <- load_raw({{id}})

dataset <- load_result_raw$dataset
name <- load_result_raw$name
target <- load_result_raw$target

load_result_imputed <- load_imputed({{id}}, 'mice')

train <- load_result_imputed$train
test <- load_result_imputed$test

pos=train[1, target]
train[, target] <- factor(unlist(lapply(train[, target], function(x) ifelse(x==pos, 1, 0))), levels=c(1, 0))
test[, target] <- factor(unlist(lapply(test[, target], function(x) ifelse(x==pos, 1, 0))), levels=c(1, 0))

fencoder = po("encode", method = "one-hot",
              affect_columns = selector_type("factor"))
learner <- lrn('classif.kknn', predict_type='prob')
pipe = fencoder %>>% learner
glearner = GraphLearner$new(pipe)
glearner$predict_type <- 'prob'

result <- train_and_test(train=train, test=test, learner=glearner, target=target, title=paste0('kNN + mice + ', name))

test_data[nrow(test_data)+1, ] <- c('kNN', 'mice', name, result$test_auc, result$test_bacc, result$test_mcc)
```

### `r name` {.tabset .tabset-fade .tabset-pills}

#### Crossvalidation results
```{r kNN_mice_{{id}}_crossvalidation, echo=FALSE, fig.align='center', fig.width=10, fig.height=5, out.width='100%', warning=FALSE, message=FALSE}
result$cv_plot
```

#### Imputation times
```{r kNN_mice_{{id}}_times, echo=FALSE}
times <- read.csv('./time_data/mice/time_data.csv')
cat(paste('Imputation time: ', round(times[times[['dataset']]==name, 'imputation_time'], 3)))
```

#### Test set results
```{r kNN_mice_{{id}}_measures, echo=FALSE}
cat(paste('Test set AUC: ', round(result$test_auc, 3)))
cat(paste('Test set BACC: ', round(result$test_bacc, 3)))
cat(paste('Test set MCC: ', round(result$test_mcc, 3)))
```

#### Missings overview
```{r kNN_mice_{{id}}_overview, echo=FALSE, fig.align='center', fig.width=8, fig.height=6, warning=FALSE, message=FALSE}
gg_miss_var(dataset, show_pct=TRUE)
```
