```{r basic_{{id}}, include=FALSE, warning=FALSE, message=FALSE}
load_result <- load({{id}})

name <- load_result$name
dataset <- load_result$dataset
target <- load_result$target

pos=dataset[1, target]
dataset[, target] <- factor(unlist(lapply(dataset[, target], function(x) ifelse(x==pos, 1, 0))), levels=c(1, 0))

learner <- lrn('classif.ranger', predict_type='prob')
result <- train_and_test(dataset, imputer=impute_basic, learner=learner, target=target, positive='1', title=paste0(name, ' + basic (median/mode)'))

time_data[nrow(time_data)+1, ] <- c('basic_(median/mode)', name, result$train_dataset_imputation_time, result$test_dataset_imputation_time)
test_data[nrow(test_data)+1, ] <- c('basic_(median/mode)', name, result$test_auc, result$test_bacc, result$test_mcc)
```

<div class="tab">
  <button class="btn btn-primary" onclick="openCity(event, 'Crossvalidation results')">Crossvalidation results</button>
  <button class="btn btn-primary" onclick="openCity(event, 'Imputation times')">Imputation times</button>
  <button class="btn btn-primary" onclick="openCity(event, 'Test set results')">Test set results</button>
  <button class="btn btn-primary" onclick="openCity(event, 'Missings overview')">Missing overview</button>
</div>

<div id="Crossvalidation results" class="tabcontent">
```{r basic_{{id}}_crossvalidation, echo=FALSE, fig.align='center', fig.width=10, fig.height=5, out.width='100%', warning=FALSE, message=FALSE}
result$cv_plot
```
</div>

<div id="Imputation times" class="tabcontent">
```{r basic_{{id}}_times, echo=FALSE}
cat(paste('Train set imputation time: ', round(result$train_dataset_imputation_time, 3)))
cat(paste('Test set imputation time: ', round(result$test_dataset_imputation_time, 3)))
```
</div>

<div id="Test set results" class="tabcontent">
```{r basic_{{id}}_measures, echo=FALSE}
cat(paste('Test set AUC: ', round(result$test_auc, 3)))
cat(paste('Test set BACC: ', round(result$test_bacc, 3)))
cat(paste('Test set MCC: ', round(result$test_mcc, 3)))
```
</div>

<div id="Missings overview" class="tabcontent">
```{r basic_{{id}}_overview, echo=FALSE, fig.align='center', fig.width=8, fig.height=6, warning=FALSE, message=FALSE}
gg_miss_var(dataset, show_pct=TRUE)
```
</div>